version: '3.7'

networks:
  default:
    name: "$ProjectName_stack_network"
    attachable: true

services:
  prometheus:
    image: "$PrometheusImageName"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      # - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=180d'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    ports:
      - '9090:9090'
    deploy:
      placement:
        constraints:
          - node.role == manager
  grafana:
    image: "$GrafanaImageName"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123456
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    deploy:
      placement:
        constraints:
          - node.role == manager