version: '3.7'

networks:
  default:
    name: "$ProjectName_stack_network"
    attachable: true

services:
  prometheus:
    image: "$PrometheusImageName"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    deploy:
      placement:
        constraints:
          - node.hostname==$ManagerNodeName

  grafana:
    image: "$GrafanaImageName"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123456
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    deploy:
      placement:
        constraints:
          - node.hostname==$ManagerNodeName