{
 "title": "Streaming Service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "GetStreamingUrl API Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{controller=\"CloudRock\", action=\"GetStreamingUrl\"}[5m])",
     "legendFormat": "{{instance}}:{{code}}"
    }
   ]
  },
  {
   "title": "GetStreamingUrl Response Time AVG",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{controller=\"CloudRock\", action=\"GetStreamingUrl\"}[5m])) by (le)) * 1000"
    }
   ]
  },
  {
   "title": "Get Data and Serialize Response Time AVG",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(GetStreamingUrlFromApiTimeSummary_sum[2m])) by (job) / sum(rate(GetStreamingUrlFromApiTimeSummary_count[2m])) by (job)"
    }
   ]
  },
  {
   "title": "GetStreamingUrl Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{controller=\"CloudRock\", action=\"GetStreamingUrl\"}[5m])) by (le)) * 1000",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Get Data From CloudRock Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(GetCloudRockDataFromApiTimeSummary_sum[2m])) by (job) / sum(rate(GetCloudRockDataFromApiTimeSummary_count[2m])) by (job)",
     "legendFormat": "ResponseTime"
    }
   ]
  },
  {
   "title": "Get Data and Serialize Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(GetStreamingUrlFromApiTimeSummary_sum[2m])) by (job) / sum(rate(GetStreamingUrlFromApiTimeSummary_count[2m])) by (job)",
     "legendFormat": "ResponseTime"
    }
   ]
  },
  {
   "title": "GetLiveStreamingMatches Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{controller=\"Match\", action=\"GetLiveStreamingMatches\"}[5m])",
     "legendFormat": "{{instance}}:{{code}}"
    }
   ]
  },
  {
   "title": "GetLiveStreamingMatches Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{controller=\"Match\", action=\"GetLiveStreamingMatches\"}[5m])) by (le)) * 1000",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Thread Pool Worker Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "dotnet_threadpool_num_threads{job=\"streamingservice\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Thread Pool Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(dotnet_threadpool_queue_length_sum{job=\"streamingservice\"}[5m]))/sum(rate(dotnet_threadpool_queue_length_count{job=\"streamingservice\"}[5m]))",
     "legendFormat": "Queue Length"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"streamingservice\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "process_working_set_bytes{job=\"streamingservice\"} / 1024 / 1024",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}